#ifndef STATE_H
#define STATE_H

// Enumerations for states
enum State {
  IDLE,
  DRIVING,
  CHANGING_AZIMUTH,
  CHANGING_AIM,
  CHANGING_MOTOR1_RPM,
  CHANGING_MOTOR2_RPM,
  CHECKING_AZIMUTH,
  CHECKING_AIM,
  CHECKING_MOTOR1_RPM,
  CHECKING_MOTOR2_RPM,
  LAUNCHING,
  ERROR
};

#endif